on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/johanberrioSS/Actions/.github/actions
      with:
        who-to-greet: 'Mona the Octocat'
    # Usa los resultados del paso `hello`
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
