name: create branch release

on:
  push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: ./
          with:
            # Optional but recommended
            # Defaults to "Apply automatic changes"
            commit_message: Apply automatic changes
            # Optional branch name where commit should be pushed to
            # Defaults to the current branch
            branch: master
  build:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Create/Update the branch
        uses: julb/action-manage-branch@v1
        with:
          name: release_v5.6.0_sprint1
          state: present
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}