name: send email

on: push

env: mensaje

jobs:
    job1:

        name: sender
        runs-on: windows-latest
    
        steps:
    
        -uses: actions/checkout@v2
    
        -uses: ./action-2

        -run: Se ha enviado un correo

