name: send email

on: push

env: mensaje

jobs:
    job1:
        name: sender
        runs-on: windows-latest
    
    steps:
    
        -name: unique step
    
        -uses: actions/checkout@v2
    
        -uses: 
    
        -run: Se ha enviado un correo