name: send email

on: push

env: 

    variable: mensaje

jobs:
    job1:

        name: sender
        runs-on: ubuntu-latest
    
        steps:
    
        - uses: actions/checkout@v
    
        - uses: ./action-2

        - run: echo Se ha enviado un correo

