name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a welcome message
      run: echo Hola Johan, bienvenido
    - name: Run a second message
      run: |
          echo Esto es una prueba,
          echo has creado tu primer action
      
